---
- name: "APT: install FreeIPA Client"
  ansible.builtin.apt:
    pkg:
      - freeipa-client
      - sssd-idp
      - sssd-kcm
      - sssd-tools
      - krb5-pkinit
    state: present
  when: ansible_os_family == 'Debian'

- name: "DNF: install FreeIPA Client"
  ansible.builtin.dnf:
    name:
      - freeipa-client
    state: present
  when: ansible_os_family == 'RedHat'

- name: "Fix up paths in sssd idp support"
  ansible.builtin.replace:
    path: /etc/krb5.conf.d/sssd_enable_idp
    regexp: "/lib64/"
    replace: "/lib/x86_64-linux-gnu/"
  when: ansible_os_family == 'Debian'

- name: "See if freeipa is enrolled"
  ansible.builtin.stat:
    path: "/etc/ipa/default.conf"
  register: ipa_enrolled

- name: "Set Domain"
  ansible.builtin.set_fact:
    domain: "{{ (inventory_hostname | split('.'))[1:] | join('.') }}"

- name: "Enroll client"
  ansible.builtin.command: ipa-client-install --force-join --mkhomedir --ssh-trust-dns --unattended --server="{{ auth_freeipa_server }}" --domain="{{ domain }}"
    --principal="{{ auth_freeipa_enroll_user }}" --password="{{ auth_freeipa_enroll_pass }}"
  when: not ipa_enrolled.stat.exists

- name: "Debian: Install IPA pam-auth-update module"
  copy:
    src: pam-auth-update-ipa
    dest: /usr/share/pam-configs/ipa
    owner: root
    mode: 0644
  register: pam_auth_update
  when: ansible_os_family == 'Debian'

- name: "Debian: Configure PAM"
  ansible.builtin.command: "pam-auth-update --disable sss sss-smart-card-optional sss-smart-card-required --enable ipa mkhomedir"
  when: ansible_os_family == 'Debian' and pam_auth_update.changed

- name: "Make sure sssd enumerate is enabled and sudo can use kerberos"
  community.general.ini_file:
    path: /etc/sssd/sssd.conf
    section: "domain/{{ domain }}"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { "key": "enumerate", "value": "True" }
    - { "key": "pam_gssapi_services", "value": "sudo, sudo-i" }
  notify: restart_sssd

- name: "Redhat: sudo allow gssapi auth"
  lineinfile:
    path: "/etc/pam.d/{{ item }}"
    line: "auth sufficient pam_sss_gss.so"
    insertbefore: "^auth.*system-auth.*"
  with_items:
    - "sudo"
    - "sudo-i"
  when: ansible_os_family == 'RedHat'
