---
- name: "APT: install FreeIPA Client"
  ansible.builtin.apt:
    pkg:
      - freeipa-client
      - sssd-idp
      - sssd-kcm
      - sssd-tools
      - krb5-pkinit
    state: present
  when: ansible_os_family == 'Debian'

- name: "DNF: install FreeIPA Client"
  ansible.builtin.dnf:
    name:
      - freeipa-client
    state: present
  when: ansible_os_family == 'RedHat'

- name: "Fix up paths in sssd idp support"
  ansible.builtin.replace:
    path: /etc/krb5.conf.d/sssd_enable_idp
    regexp: "/lib64/"
    replace: "/lib/x86_64-linux-gnu/"
  when: ansible_os_family == 'Debian'

- name: "See if freeipa is enrolled"
  stat:
    path: "/etc/ipa/default.conf"
  register: ipa_enrolled

- name: "Set Domain"
  set_fact:
    domain: "{{ (inventory_hostname | split('.'))[1:] | join('.') }}"

- name: "Enroll client"
  shell: ipa-client-install --force-join --mkhomedir --ssh-trust-dns --unattended --server="{{ auth_freeipa_server }}" --domain="{{ domain }}" --principal="{{ auth_freeipa_enroll_user }}" --password="{{ auth_freeipa_enroll_pass }}"
  when: not ipa_enrolled.stat.exists

- name: "Fix common-auth to work with IDP"
  ansible.builtin.blockinfile:
    path: /etc/pam.d/common-auth
    insertbefore: '^#*auth.*\[.*\].*pam_unix.so nullok'
    block: |
      auth  [default=1 ignore=ignore success=ok]  pam_usertype.so isregular
      auth  [default=1 ignore=ignore success=ok]  pam_localuser.so
      auth  sufficient          pam_unix.so nullok
      auth  [default=1 ignore=ignore success=ok]  pam_usertype.so isregular
      auth  sufficient          pam_sss.so forward_pass
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- SSSD IDP SUPPORT"
  when: ansible_os_family == 'Debian'

- name: "Comment out lines that should no longer be used for auth"
  ansible.builtin.replace:
    path: /etc/pam.d/common-auth
    regexp: "{{ item.regexp }}"
    replace: "{{ item.val }}"
  with_items:
    - { "regexp": '^(auth.*\[.*\].*pam_unix.so nullok)',        "val": '#\1' }
    - { "regexp": '^(auth.*\[.*\].*pam_sss.so use_first_pass)', "val": '#\1' }
  when: ansible_os_family == 'Debian'

- name: "Make sure sssd enumerate is enabled and sudo can use kerberos"
  community.general.ini_file:
    path: /etc/sssd/sssd.conf
    section: "domain/{{ domain }}"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { "key": "enumerate",           "value": "True" }
    - { "key": "pam_gssapi_services", "value": "sudo, sudo-i" }
  notify: restart_sssd

- name: "sudo allow gssapi auth"
  lineinfile:
    path: "/etc/pam.d/{{ item }}"
    line: "auth sufficient pam_sss_gss.so"
    insertbefore: "{{ '^auth.*system-auth.*' if ansible_os_family == 'RedHat' else '@include common-auth' }}"
  with_items:
    - "sudo"
    - "sudo-i"
